/**
 * API types generated from backend OpenAPI spec.
 * Run `npm run generate-types` to regenerate from the backend OpenAPI schema.
 *
 * This file will be auto-generated by openapi-typescript.
 * Manual types are provided as placeholders until the backend is running.
 */

// Placeholder types until generated from OpenAPI spec
export interface paths {}
export interface components {}
